name: scheduler
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  dart_json_mapper: ^2.2.12+1
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_screenutil: ^5.9.3
  get_it: ^7.7.0
  go_router: ^14.2.3
  google_fonts: ^6.2.1
  intl: ^0.19.0
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    
  fonts:
    
    
    - family: Montserrat
      fonts:
        - asset: fonts/montserrat/montserrat.ttf
